apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-partner-context-ui.fullname" . }}
  namespace: nab-dev
  labels:
    {{- include "application-partner-context-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "application-partner-context-ui.selectorLabels" . | nindent 4 }}
