apiVersion: v1
kind: Service
metadata:
  name: {{ include "device-registry-service.fullname" . }}
  namespace: nab-dev
  labels:
    {{- include "device-registry-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "device-registry-service.selectorLabels" . | nindent 4 }}
