# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

# Default values for NEF.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: nab-ngc-dev

# enable toleration for this POD to run on the K8S master
enable_toleration: false

image:
  repository: devnio/nef
  tag: "1.1.93"
  pullPolicy: IfNotPresent

service:
  name: nefservice
  type: NodePort

configmap:
  name: configmapNEF
  nef: nef-cm
  oauth2: oauth2-cm
  certs: certs-cm

#Agent
agent:
  image: devnio/opentelemetry-collector-dev:1.1.1
  configmapName: otel-nef-agent-config-vol
  configMap: otel-nef-agent-conf
  name: otel-nef-agent
  rootca:  /root/CA/cert.pem
  servername: otel-collector.telemetry.svc
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  opencensusport: 55678  #OpenCensus receiver port
  receivers: opencensus
  receiver:
    opencensus:
      endpoint: localhost:55678
  
  exporters: opencensus
  exporter:
    opencensus:
      endpoint: otel-collector.telemetry.svc:55668
