apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator-service.fullname" . }}
  namespace: nab-dev
  labels:
    {{- include "operator-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "operator-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "operator-service.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets: [{ name: dockerregcred }]
        
      {{- end }}
      serviceAccountName: {{ include "operator-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ENV_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_SERVER_PORT
            - name: ENV_SWAGGER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_SWAGGER_USERNAME
            - name: ENV_SWAGGER_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_SWAGGER_PASSWORD
            - name: ENV_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_PROFILE
            - name: ENV_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_APP_NAME
            - name: ENV_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_DB_URL
            - name: ENV_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_DB_USERNAME
            - name: ENV_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_DB_PASSWORD
            - name: ENV_KEYCLOAK_URL
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_KEYCLOAK_URL
            - name: ENV_KEYCLOAK_CONTEXT_PATH
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_KEYCLOAK_CONTEXT_PATH
            - name: ENV_IDENTITY_PROVIDER
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_IDENTITY_PROVIDER
            - name: ENV_KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_KEYCLOAK_REALM
            - name: ENV_KEYCLOAK_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_KEYCLOAK_SERVICE_NAME
            - name: ENV_KEYCLOAK_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_KEYCLOAK_USERNAME
            - name: ENV_KEYCLOAK_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_KEYCLOAK_PASSWORD
            - name: ENV_KEYCLOAK_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_KEYCLOAK_CLIENT
            - name: ENV_PRINT_PAYLOAD
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_PRINT_PAYLOAD
            - name: ENV_ROOT_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_ROOT_LOG_LEVEL
            - name: ENV_NIO_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_NIO_LOG_LEVEL
            - name: ENV_FLAYWAY_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: operatorconfig
                  key: ENV_FLAYWAY_LOG_LEVEL 
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
