# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  labels:
    service: "{{ .Values.service.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  type: "{{ .Values.service.type }}"
  ports:
    - port: 8050
      targetPort: 8050
      nodePort: 30053
      #    The below format does not work as helm charts reports expected variable
      #    is of type integer but string is passed. Alternatively if we remove
      #    the quotes and int. ansible reports a lint warning
      #    nodePort: "{{ .Values.service.nodePort | int }}"
      protocol: TCP
      name: cnca
    - port: 8051
      targetPort: 8051
      nodePort: 30054
      protocol: TCP
      name: nef
# targetPort and nodePort are same because targetPort is shared by AF
# outside cluster to consumers. Ansible replaces the targetPort in af.json
# with nodePort
    - port: 30055
      targetPort: 30055
      nodePort: 30055
      protocol: TCP
      name: afnotifyws
  selector:
    service: "{{ .Values.service.name }}"
