apiVersion: v1
kind: ConfigMap
metadata:
  name: niop
  namespace: nab-dev
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/niotis?enabledTLSProtocols=TLSv1.2"
  SPRING_DATASOURCE_USERNAME: "niotis"
  SPRING_DATASOURCE_PASSWORD: "niotis"
  COM_NIO_CONFIG_V2PLATFORMURL: "http://platform-configuration-service:9080/cc/platform-configuration-service"
  COM_NIO_CONFIG_V2DEVICEURL: "http://device-registry-service:9083/dvc/device-registry-service"
  COM_NIO_CONFIG_V2PARTNERURL: "http://application-partner-service:9081/apc/application-partner-service"
  COM_NIO_CONFIG_V2PARTNERUIURL: "https://partner.nabstract.io/partner"
  COM_NIO_CONFIG_V2MONETIZATIONURL: "http://monetization-service:8083/mzc/monetization-service"
  COM_NIO_CONFIG_V2OPERATORURL: "http://operator-service:9084/oc/operator-service"
  COM_NIO_CONFIG_V2AUTHSERVICEURL: "http://niop-auth-srv:8088/ac/auth-service"
  COM_NIO_CONFIG_V2SIMSWAPSERVICEURL: "http://niop-sim-swap-srv.nab-dev.svc.cluster.local:9087/sim-swap-service"
  COM_NIO_CONFIG_V2LOCATIONSERVICEURL: "http://niop-device-location-srv.nab-dev.svc.cluster.local:9088/device-location-service"
  COM_NIO_CONFIG_V2NUMBERVERIFYSERVICEURL: "http://niop-number-verification-srv.nab-dev.svc.cluster.local:9089/number-verification-service"
  GOOGLEMAP_DEFAULT_LAT: "21.7679"
  GOOGLEMAP_DEFAULT_LONG: "78.8718"
  APP_TIMEZONE: "Asia/Kolkata"
