apiVersion: v1
kind: ConfigMap
metadata:
  name: niop
  namespace: nab-dev
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/niotis?enabledTLSProtocols=TLSv1.2"
  SPRING_DATASOURCE_USERNAME: "niotis"
  SPRING_DATASOURCE_PASSWORD: "niotis"
  COM_NIO_CONFIG_V2PLATFORMURL: "http://platform-configuration-service:9080/cc/platform-configuration-service"
  COM_NIO_CONFIG_V2DEVICEURL: "http://device-registry-service:9083/dvc/device-registry-service"
  COM_NIO_CONFIG_V2PARTNERURL: "http://application-partner-service:9081/apc/application-partner-service"
  COM_NIO_CONFIG_V2PARTNERUIURL: "https://partner.nabstract.io/partner"
  COM_NIO_CONFIG_V2MONETIZATIONURL: "http://monetization-service:8083/mzc/monetization-service"
  COM_NIO_CONFIG_V2OPERATORURL: "http://operator-service:9084/oc/operator-service"
  COM_NIO_CONFIG_V2AUTHSERVICEURL: "http://niop-auth-srv:8088/ac/auth-service"
