# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.service.name }}"
  labels:
    service: "{{ .Values.service.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  type: NodePort
  ports:
    - port: 8060
      nodePort: 31573
      targetPort: 8060
      protocol: TCP
      name: af
    - port: 9051
      nodePort: 31574
      targetPort: 9051
      protocol: TCP
      name: notification
    - port: 10051
      nodePort: 31572
      targetPort: 10051
      protocol: TCP
      name: sslnotif
  selector:
    service: "{{ .Values.service.name }}"
