apiVersion: v1
kind: ConfigMap
metadata:
  name: apsconfig
  namespace: nab-dev
data:
  ENV_SERVER_PORT: "9081"
  ENV_PROFILE: "dev"
  ENV_APP_NAME: "application-partner-service"
  ENV_DB_URL: "jdbc:postgresql://postgres:5432/nio_apc_db"
  ENV_DB_USERNAME: "postgres"
  ENV_DB_PASSWORD: "admin"
  ENV_SWAGGER_USERNAME: "admin"
  ENV_SWAGGER_PASSWORD: "nabstract"
  ENV_MONETIZATION_URL: "http://monetization-service:8083"
  ENV_MONETIZATION_CONTEXT_PATH: "/mzc/monetization-service"
  ENV_MONETIZATION_SERVICE_NAME: "monetization-service"
  ENV_MONETIZATION_RETRY_COUNT: "1"
  ENV_MONETIZATION_RETRY_INTERVAL: "3000"
  ENV_MONETIZATION_CON_TIMEOUT: "1000"
  ENV_KEYCLOAK_URL: "http://keycloak.keycloak.svc.cluster.local:8080"
  ENV_KEYCLOAK_REALM: "nabstract"
  ENV_KEYCLOAK_CONTEXT_PATH: ""
  ENV_KEYCLOAK_SERVICE_NAME: "keycloak-service"
  ENV_KEYCLOAK_USERNAME: "admin"
  ENV_KEYCLOAK_PASSWORD: "Abm!n#91o3"
  ENV_KEYCLOAK_CLIENT: "admin-cli"
  ENV_IDENTITY_PROVIDER: "keycloak"
  ENV_OPERATOR_URL: "http://operator-service:9084"
  ENV_OPERATOR_CONTEXT_PATH: "/oc/operator-service"
  ENV_OPERATOR_SERVICE_NAME: "operator-service"
  ENV_OPERATOR_RETRY_COUNT: "1"
  ENV_OPERATOR_RETRY_INTERVAL: "3000"
  ENV_OPERATOR_CON_TIMEOUT: "1000"
  ENV_NIOP_URL: "http://niop-niotis:20080"
  ENV_NIOP_CONTEXT_PATH: ""
  ENV_NIOP_SERVICE_NAME: "niop-service"
  ENV_NIOP_RETRY_COUNT: "1"
  ENV_NIOP_RETRY_INTERVAL: "3000"
  ENV_NIOP_CON_TIMEOUT: "1000"
  
 
  
