apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-partner-service.fullname" . }}
  namespace: nab-dev
  labels:
    {{- include "application-partner-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }}
      name: http
  selector:
    {{- include "application-partner-service.selectorLabels" . | nindent 4 }}
