apiVersion: v1
kind: Service
metadata:
  name: {{ include "monetization-service.fullname" . }}
  namespace: nab-dev
  labels:
    {{- include "monetization-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "monetization-service.selectorLabels" . | nindent 4 }}
